#!/bin/bash

set -euo pipefail

member_account_id="${1}"
repetitions="${2}"
output_dir="out"

mkdir --parents "${output_dir}"

poetry run python -m botocove.experimental_runners --list-runners \
| xargs -I {} ./profile_runner {} "${member_account_id}" "${repetitions}" "${output_dir}"/{}.csv
